---
output:
  html_document
---

## nextHIV Report {.tabset}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r loadlibraries}
suppressPackageStartupMessages(library(rethinker))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggforce))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(xtable))
```

```{r setglobals}
host <- "localhost"
port <- 28015
authKey <- NULL
v <- "V0_4"
db <- "nexthiv"
pid <- "CFAR_PID"
```

```{r definefunctions}
get_list <- function(db,tbl,maxResults=10000,host="localhost",port=28015,authKey=NULL,v="V0_4"){
  connection <- openConnection(host = host, port = port, authKey = authKey, v = v)
  r() -> query
  query$db(db)
  query$table(tbl)
  cursor <- query$run(connection)
  l <- cursorToList(cursor,maxResults=maxResults)
  close(connection)
  return(l)
}
get_table <- function(db,tbl,maxResults=10000,host="localhost",port=28015,authKey=NULL,v="V0_4"){
  l <- get_list(db,tbl,maxResults,host,port,authKey,v)
  df <- do.call(rbind, lapply(l, data.frame, stringsAsFactors=FALSE))
  return(df)
}
# Need to add column filters
```

```{r loadtables}
demographics <- get_table(db,"demographics")
sequences <- get_table(db,"sequences")
clustering <- get_table(db,"clustering")
resistance <- get_list(db,"resistance")
```

```{r makemastertable}
master <- merge(sequences,clustering[,1:3],by.x="id",by.y="id")
master <- merge(master,demographics,by="CFAR_PID")
o <- order(master$CFAR_PID,as.double(master$AGE_AT_SEQUENCE))
master <- master[o,]
master$BASELINE <- !duplicated(master$CFAR_PID)
```

### Summary

Date of report: `r Sys.Date()`

No. of individuals: `r length(unique(sequences$CFAR_PID))`

No. of sequences: `r length(sequences$CFAR_PID)`

### Demographics


```{r}
p <- ggplot(demographics,aes(x=as.double(YEAR_OF_COHORT_ENTRY)))+geom_bar()+xlab("Year of cohort entry")+ylab("Count")
ggplotly(p)
```


```{r}
p <- ggplot(demographics,aes(x=as.double(AGE_AT_ENROLLMENT)))+geom_histogram(binwidth=1)+xlab("Age at cohort entry")+ylab("Count")
ggplotly(p)
```


```{r}
p <- ggplot(demographics,aes(x=SEX))+geom_bar()+xlab("Gender")+ylab("Count")+scale_x_discrete(labels=c("Female","Male"))
ggplotly(p)
```

```{r}
p <- ggplot(demographics,aes(x=RISK1))+geom_bar()+xlab("Risk behavior")+ylab("Count")
ggplotly(p)
```


```{r}
zip3 <- demographics$postCode3
ztbl <- table(zip3)
rarezip <- names(ztbl)[ztbl<=5]
zip3[zip3%in%rarezip] <- "Other"
x <- data.frame(ZIP3=zip3)
p <- ggplot(x,aes(x=ZIP3))+geom_bar()+xlab("ZIP3 code")+ylab("Count")
ggplotly(p)
```


```{r}
cntry <- demographics$COUNTRY_OF_ORIGIN
cntry[cntry==""] <- "MISSING"
ctbl <- table(cntry)
rarecntry <- names(ctbl)[ctbl<=5]
cntry[cntry%in%rarecntry] <- "OTHER"
x <- data.frame(Country=factor(cntry,levels=names(sort(table(cntry),decreasing=TRUE))))
p <- ggplot(x,aes(x=Country))+geom_bar()+xlab("Country of origin")+ylab("Count")+ theme(axis.text.x = element_text(angle = 90, hjust = -1))
ggplotly(p)
```

```{r}
races <- c("Undefined","Caucasian","African American","Hispanic","Native American","Asian","Pacific Islander","Indian","Middle Eastern","African","Mixed")
race <- as.integer(demographics$RACE)
race <- race+1
race <- races[race]
rtbl <- table(race)
rarerace <- names(rtbl)[rtbl<=5]
race[race%in%rarerace] <- "Other"
x <- data.frame(Race=factor(race,levels=names(sort(table(race),decreasing=TRUE))))
p <- ggplot(x,aes(x=Race))+geom_bar()+xlab("Race")+ylab("Count")+ theme(axis.text.x = element_text(angle = 90, hjust = -1))
ggplotly(p)
```

### Sequences


```{r}
df <- as.data.frame.table(table(table(sequences$CFAR_PID)))
names(df) <- c("Number","Count")
p <- ggplot(df,aes(x=Number,y=Count))+geom_bar(stat="identity")+xlab("Sequences per individual")+ylab("Count")
ggplotly(p)
```

<br>

```{r}
datatable(df)
```


### Clustering


```{r}
d <- master
o <- order(d$CFAR_PID,d$MINDST)
idx <- !duplicated(d$CFAR_PID)
d <- d[idx,]
p <- ggplot(d,aes(x=as.double(MINDST)))+geom_histogram(binwidth=0.001)+xlab("Minimum genetic distance")+ylab("Count")
ggplotly(p)
```

```{r}
p <- ggplot(d,aes(y=as.double(MINDST),x=SEX))+geom_sina(aes(col=SEX))+xlab("Gender")+ylab("Distance")+scale_x_discrete(labels=c("Female","Male"))+theme(legend.position="none")
ggplotly(p)
```

```{r}
p <- ggplot(d,aes(y=as.double(MINDST),x=RISK1))+geom_sina(aes(col=RISK1))+xlab("Risk behavior")+ylab("Distance")+theme(legend.position="none")
ggplotly(p)
```


